# .streamlit/config.toml

[server]
# Use "watchdog" for more reliable file watching
fileWatcherType = "watchdog"

# Allow running from anywhere (helpful for some deployment platforms)
headless = true
enableCORS = false
port = 8501
enableXsrfProtection = true  # Enable XSRF protection to prevent CSRF attacks.

[theme]
base="light"
primaryColor="#0b87a2"
secondaryBackgroundColor="#d4dce0"
